SELECT 
    d.DEPARTMENT_NAME,
    p.SALARY,
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS EMPLOYEE_NAME,
    e.EMP_ID AS EMPLOYEE_ID,
    e.EMP_ID AS EMP_ID,
    TIMESTAMPDIFF(YEAR, e.DOB, CURDATE()) AS AGE
FROM EMPLOYEE e
JOIN PAYMENTS p ON e.EMP_ID = p.EMP_ID
JOIN DEPARTMENT d ON e.DEPARTMENT = d.DEPARTMENT_ID
WHERE DAY(LAST_DAY(p.PAYMENT_TIME)) != DAY(p.PAYMENT_TIME)
AND p.SALARY = (
    SELECT MAX(p2.SALARY)
    FROM PAYMENTS p2
    JOIN EMPLOYEE e2 ON p2.EMP_ID = e2.EMP_ID
    WHERE e2.DEPARTMENT = e.DEPARTMENT
    AND DAY(LAST_DAY(p2.PAYMENT_TIME)) != DAY(p2.PAYMENT_TIME)
)
ORDER BY d.DEPARTMENT_NAME;
